# 尼采谱系学-Thinkers-Wiki 网站部署工作流程
# 用于自动将静态网站内容部署到 GitHub Pages
name: Deploy Thinkers-Wiki to GitHub Pages

on:
  # 在推送到 main 分支时自动触发部署
  push:
    branches: ["main"]

  # 允许从 Actions 选项卡手动触发此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许只有一个并发部署，跳过在进行中运行和最新排队运行之间的排队运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 单一部署作业，因为我们只是部署静态内容
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 步骤1: 检出代码仓库
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          # 确保检出完整的提交历史，这对于某些工具可能是必要的
          fetch-depth: 0
      
      # 步骤2: 设置 GitHub Pages
      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v5
        with:
          # 配置为静态网站，不使用 Jekyll 处理
          # 这很重要，因为我们的网站是纯静态 HTML/CSS/JS
          enablement: force
          static_site_generator: none
      
      # 步骤3: 上传网站文件作为构建产物
      - name: 上传网站文件
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传整个仓库目录作为网站内容
          # 这包括 index.html、尼采谱系学-Thinkers-Wiki.html 和 timeline-interaction.js
          path: '.'
      
      # 步骤4: 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
